Lint/EndAlignment:
  Enabled: false

# Offense count: 2
Metrics/AbcSize:
  Max: 20

# Offense count: 74
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/users/omniauth_callbacks_controller.rb"
    - "app/helpers/users/omniauth_helper.rb"

# Offense count: 28
Style/Documentation:
  Enabled: false
